version: "3.9"
services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5436:5432"